AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: description
Metadata:
  Name: init001
  Author: relly
  Version: 1.0.110
  Repo: 'https://github.com/relly/fnhub'
  Keywords:
    - backand
    - init
    - key3
  License: mit
