AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: description
Metadata:
  Name: init001
  Author: relly
  Version: 3.0.123
  Entrypoint: index.js
  Repo: 'https://github.com/relly/fnhub'
  Keywords:
    - backand
  License: mit
codeUri: 'http://fnhub.backand.io/module@3.0.111.zip'
Resources:
  fn2:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs4.3
      CodeUri: 'http://fnhub.backand.io/module@3.0.123.zip'
      Environment:
        Variables: {}
  fn3:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs4.3
      CodeUri: 'http://fnhub.backand.io/module@3.0.123.zip'
      Environment:
        Variables: {}
