Description: test itay
Metadata:
  Name: fnhub-cli
  Author: itay
  Version: 1.0.0
  Repo: 'https://github.com/backand/fnhub-cli'
  Keywords:
    - fnhub-cli
  License: ISC
Resources:
  fnhub-cli:
    Type: 'AWS::Serverless::Function'
    Properties:
      Description: test itay
      Handler: index.handler
      Runtime: nodejs4.3
      CodeUri: 's3://bucket/zipfile'
