AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation sample template that contains a single Lambda function
  behind an API Gateway
Resources:
  GreetingLambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile:
          Fn::Join:
          - "\n"
          - - "'use strict';"
            - ''
            - "// Greeter Lambda"
            - exports.handler = (event, context, callback) => {
            - "  console.log('Event:', JSON.stringify(event));"
            - "  const name = event.name || 'World';"
            - "  const response = {event: event, context:context};"
            - "  callback(null, response);"
            - "};"
      Description: A greeting function
      FunctionName: GreetingLambda
      Handler: index.handler
      Role:
        Fn::GetAtt:
        - LambdaExecutionRole
        - Arn
      Runtime: nodejs4.3
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
  GreetingApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: Greeting API
      Description: API used for Greeting requests
      FailOnWarnings: true
  LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:invokeFunction
      FunctionName:
        Fn::GetAtt:
        - GreetingLambda
        - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
        - ''
        - - 'arn:aws:execute-api:'
          - Ref: AWS::Region
          - ":"
          - Ref: AWS::AccountId
          - ":"
          - Ref: GreetingApi
          - "/*"
  ApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
    - GreetingRequest
    Properties:
      RestApiId:
        Ref: GreetingApi
      StageName: LATEST
  GreetingResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId:
        Ref: GreetingApi
      ParentId:
        Fn::GetAtt:
        - GreetingApi
        - RootResourceId
      PathPart: greeting
  GreetingRequest:
    DependsOn: LambdaPermission
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: ANY
      Integration:
        Type: AWS
        IntegrationHttpMethod: POST
        Uri:
          Fn::Join:
          - ''
          - - 'arn:aws:apigateway:'
            - Ref: AWS::Region
            - ":lambda:path/2015-03-31/functions/"
            - Fn::GetAtt:
              - GreetingLambda
              - Arn
            - "/invocations"
        IntegrationResponses:
        - StatusCode: 200
        RequestTemplates:
          application/json:
            Fn::Join:
            - ''
            - - "{"
              - '  "param1": "$input.params(''param1'')",'
              - '  "param2": "$input.params(''param2'')"'
              - "}"
      RequestParameters:
        method.request.querystring.param1: false
        method.request.querystring.param2: false
      ResourceId:
        Ref: GreetingResource
      RestApiId:
        Ref: GreetingApi
      MethodResponses:
      - StatusCode: 200
Outputs:
  RootUrl:
    Description: Root URL of the API gateway
    Value:
      Fn::Join:
      - ''
      - - https://
        - Ref: GreetingApi
        - ".execute-api."
        - Ref: AWS::Region
        - ".amazonaws.com"
